import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#474746",
        background: "#161C24",
        "tertiary-container": "#aba9a9",
        "on-error": "#690005",
        surface: "#161C24",
        "on-secondary-fixed-variant": "#474746",
        "surface-container-low": "#1F262E",
        "inverse-primary": "#904d00",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-background": "#FDFDFD",
        "on-tertiary-fixed-variant": "#474747",
        "surface-container-highest": "#353535",
        "primary-fixed": "#ffdcc3",
        "surface-container-lowest": "#0e0e0e",
        "surface-tint": "#F04D32",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#6e3900",
        "surface-dim": "#161C24",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-container": "#3e3e3e",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#313030",
        "surface-variant": "#353535",
        "on-primary": "#ffffff",
        error: "#ffb4ab",
        "on-primary-container": "#ffffff",
        "primary-fixed-dim": "#F04D32",
        secondary: "#c8c6c5",
        "surface-bright": "#393939",
        "on-surface": "#FDFDFD",
        "outline-variant": "#564334",
        "on-surface-variant": "#CBD5E1",
        tertiary: "#c8c6c6",
        "tertiary-fixed": "#e4e2e1",
        "on-tertiary-fixed": "#1b1c1c",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#2f1500",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary": "#303030",
        primary: "#F04D32",
        "inverse-on-surface": "#161C24",
        "error-container": "#93000a",
        "surface-container": "#252C35",
        outline: "#a48c7a",
        "on-secondary-container": "#b7b5b4",
        "primary-container": "#F04D32",
        "inverse-surface": "#FDFDFD",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "8px",
        base: "4px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        margin: "32px",
        sm: "16px",
        gutter: "24px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        h1: ["Space Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        code: ["monospace"],
        h3: ["Space Grotesk", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        h2: ["Space Grotesk", "sans-serif"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        code: ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
